package fr.campus.grog.SU.service;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import jakarta.annotation.PostConstruct;
import org.springframework.core.io.Resource;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.nio.charset.StandardCharsets;
import java.security.KeyFactory;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Base64;
import java.util.Date;
import java.util.List;

@Service
public class JwtService {

    @Value("${jwt.private-key-path}")
    private Resource privateKeyResource;

    @Value("${jwt.public-key-path}")
    private Resource publicKeyResource;

    private PrivateKey privateKey;
    private PublicKey publicKey;

    @PostConstruct
    public void init() throws Exception {
        // =========================================================================
        // 1. Load and parse the RSA Private Key (Used for SIGNING tokens)
        // =========================================================================
        // Read the raw PEM file content from the classpath resource as a UTF-8 String
        String privateKeyContent = new String(this.privateKeyResource.getInputStream().readAllBytes(),
                StandardCharsets.UTF_8);
        // Strip the PEM header/footer lines and all whitespace (newlines/spaces).
        // Java's Base64 decoder strictly expects pure Base64 characters and would fail
        // on line breaks.
        String cleanPrivateKey = privateKeyContent
                .replace("-----BEGIN PRIVATE KEY-----", "")
                .replace("-----END PRIVATE KEY-----", "")
                .replaceAll("\\s", "");
        // Decode the cleaned Base64 text back into raw cryptographic binary bytes
        byte[] privateKeyBytes = Base64.getDecoder().decode(cleanPrivateKey);
        // Standard JVM factory for RSA cryptographic operations
        KeyFactory keyFactory = KeyFactory.getInstance("RSA");
        // PKCS#8 is the standard international format for private keys generated by
        // OpenSSL.
        // Convert the binary specification into a concrete java.security.PrivateKey
        // instance.
        this.privateKey = keyFactory.generatePrivate(new PKCS8EncodedKeySpec(privateKeyBytes));

        // =========================================================================
        // 2. Load and parse the RSA Public Key (Used for VERIFYING tokens)
        // =========================================================================
        // Read the raw public key PEM file content from the classpath resource
        String publicKeyContent = new String(this.publicKeyResource.getInputStream().readAllBytes(),
                StandardCharsets.UTF_8);
        // Strip the public key PEM banners and all formatting whitespace
        String cleanPublicKey = publicKeyContent
                .replace("-----BEGIN PUBLIC KEY-----", "")
                .replace("-----END PUBLIC KEY-----", "")
                .replaceAll("\\s", "");
        // Decode the Base64 text into raw binary bytes
        byte[] publicKeyBytes = Base64.getDecoder().decode(cleanPublicKey);
        // X.509 is the standard international format for public keys.
        // Convert the specification into a concrete java.security.PublicKey instance.
        this.publicKey = keyFactory.generatePublic(new X509EncodedKeySpec(publicKeyBytes));
    }

    /**
     * Generates a signed JWT for an authenticated user using RS256 algorithm.
     *
     * @param username The subject (pseudo or UUID) of the user
     * @param roles    The list of security roles granted to the user
     * @return Compact serialized JWT string (header.payload.signature)
     */
    public String generateToken(String username, String userId, List<String> roles) {
        long nowMillis = System.currentTimeMillis();
        Date issuedAt = new Date(nowMillis);
        // Token validity: 24 hours (24 hours * 60 mins * 60 secs * 1000 ms)
        long expirationMillis = nowMillis + (24L * 60 * 60 * 1000);
        Date expirationDate = new Date(expirationMillis);
        return Jwts.builder()
                // Standard RFC 7519 'sub' (subject) claim identifying the token owner
                .subject(username)
                // Custom claim containing user id for other api that will need it (ie:Square Games)
                .claim("userId", userId)
                // Custom claim containing user roles for authorization in downstream services
                .claim("roles", roles)
                // Standard 'iat' (issued at) claim
                .issuedAt(issuedAt)
                // Standard 'exp' (expiration time) claim
                .expiration(expirationDate)
                // Cryptographically sign using our RSA private key and RS256 algorithm
                .signWith(this.privateKey, Jwts.SIG.RS256)
                // Serialize into URL-safe compact string: header.payload.signature
                .compact();
    }

    //Commodity method for test classes
    public String generateToken(String username, List<String> roles)
    {
        return generateToken(username, null, roles);
    }

    /**
     * Extracts the username (subject claim) from a signed JWT.
     *
     * @param token Compact serialized JWT string
     * @return The username embedded in the token's subject claim
     */
    public String extractUsername(String token) {
        // Parse and verify the signed JWT using our RSA public key
        Claims claims = Jwts.parser()
                // Verify the cryptographic signature using our public key
                .verifyWith(this.publicKey)
                .build()
                // Parses the compact token and validates its signature
                .parseSignedClaims(token)
                // Retrieve the payload containing all claims
                .getPayload();
        // Extract the RFC 7519 'sub' (subject) claim representing the username
        return claims.getSubject();
    }

    /**
     * Validates whether a token is authentic, untampered, and currently active.
     *
     * @param token Compact serialized JWT string
     * @return true if signature is valid and token is not expired, false otherwise
     */
    public boolean isTokenValid(String token) {
        try {
            // JJWT automatically validates the signature AND checks if expiration < now.
            // If the token is expired, forged, or malformed, it throws a JwtException.
            Jwts.parser()
                    .verifyWith(this.publicKey)
                    .build()
                    .parseSignedClaims(token);
            return true;
        } catch (JwtException | IllegalArgumentException e) {
            // Token is invalid, expired, corrupted, or null
            return false;
        }
    }

}
