spring.application.name=SU

server.port=${SU_SERVER_PORT:8081}

# Active Spring Profile (postgres or h2)
spring.profiles.active=postgres

# for JWT
jwt.private-key-path=${SU_JWT_PRIVATE_KEY_PATH:classpath:certs/private_key.pem}
jwt.public-key-path=${SU_JWT_PUBLIC_KEY_PATH:classpath:certs/public_key.pem}