spring.application.name=SU

server.port=8081

# Active Spring Profile (postgres or h2)
spring.profiles.active=postgres

# for JWT
jwt.private-key-path=classpath:certs/private_key.pem
jwt.public-key-path=classpath:certs/public_key.pem